"""Deterministic question planning from an extracted form schema."""

from collections.abc import Callable, Collection
from datetime import datetime
from decimal import Decimal, InvalidOperation

from pydantic import BaseModel, ConfigDict

from .schemas import FieldType, FormField, FormSchema, ValidationMetadata


class FormQuestion(BaseModel):
    """A display-ready question derived only from an extracted visible field."""

    model_config = ConfigDict(extra="forbid")

    field_id: str
    prompt: str
    explanation: str
    type: FieldType
    required: bool
    options: list[str]
    instruction: str


class AnswerValidation(BaseModel):
    """Deterministic backend validation outcome; never generated by the AI."""

    model_config = ConfigDict(extra="forbid")

    valid: bool
    message: str | None = None


class ConfirmedAnswer(BaseModel):
    """A user-entered value that the user has explicitly confirmed.

    This is not a validation result. Field-specific validation belongs to a
    future deterministic backend validation layer.
    """

    model_config = ConfigDict(extra="forbid")

    field_id: str
    value: str


class AnswerSession(BaseModel):
    """Confirmed answers kept separately from the extracted form."""

    model_config = ConfigDict(extra="forbid")

    form_name: str
    answers: list[ConfirmedAnswer]


def question_for_field(field: FormField) -> FormQuestion:
    """Create a question without adding information beyond the extracted field."""

    return FormQuestion(
        field_id=field.id,
        prompt=field.label,
        explanation=field.explanation,
        type=field.type,
        required=field.required,
        options=field.options.copy(),
        instruction=instruction_for_field(field),
    )


def instruction_for_field(field: FormField) -> str:
    """Build concise input guidance only from schema-defined field information."""

    label = field.label.rstrip(": ")
    parts = [f"Please enter {label}."]
    type_guidance = {
        "text": "Enter the text requested by the form.",
        "textarea": "Enter the requested details.",
        "number": "Enter a number.",
        "date": "Enter a complete date.",
        "email": "Enter an email address in the format name@example.com.",
        "phone": "Enter the phone number requested by the form.",
        "radio": "Choose one visible option.",
        "checkbox": "Choose the visible option or options that apply.",
    }
    validation = _effective_validation(field)
    if validation.value_format == "name":
        parts.append("Enter a name using letters and spaces.")
    else:
        parts.append(type_guidance[field.type])
    if validation.exact_length is not None:
        unit = "digits" if field.type == "phone" or validation.numeric_only else "characters"
        parts.append(f"The form specifies exactly {validation.exact_length} {unit}.")
    elif validation.min_length is not None or validation.max_length is not None:
        bounds = _length_instruction(validation)
        if bounds:
            parts.append(bounds)
    if validation.date_format:
        parts.append(f"Use the form's date format: {validation.date_format}.")
    if field.options:
        parts.append("Visible options: " + ", ".join(field.options) + ".")
    if field.required:
        parts.append("This field is marked required on the form.")
    notes = list(dict.fromkeys([*field.visible_instructions, *validation.instructions]))
    if notes:
        parts.append("Form note: " + " ".join(notes))
    if validation.examples:
        parts.append("Example shown on the form: " + " ".join(validation.examples))
    if validation.uncertain:
        parts.append("Some form details were unclear, so no extra restriction is being enforced.")
    return " ".join(parts)


def explain_field(field: FormField, user_question: str = "") -> str:
    """Answer a user's field question without making up a reason or requirement."""

    label = field.label.rstrip(": ")
    detail = field.explanation or f"This is the {label} field shown on the form."
    if user_question.strip().casefold().startswith("why"):
        detail += " The form does not state an additional reason for this field."
    return f"{detail} {instruction_for_field(field)}"


def validate_answer(field: FormField, value: str) -> AnswerValidation:
    """Apply basic deterministic format checks without eligibility or business rules."""

    cleaned = value.strip()
    if not cleaned:
        if field.required:
            return AnswerValidation(valid=False, message="This field is visibly marked required. Please provide a value.")
        return AnswerValidation(valid=True)

    validation_metadata = _effective_validation(field)
    if validation_metadata.confidence == "high" and validation_metadata.value_format == "name":
        letters = [character for character in cleaned if character.isalpha()]
        allowed_name_characters = all(character.isalpha() or character.isspace() or character in "-' ." for character in cleaned)
        if not allowed_name_characters or not letters:
            return AnswerValidation(
                valid=False,
                message="Please enter a name using letters, spaces, hyphens, apostrophes, or periods; do not enter digits.",
            )

    if field.type == "phone":
        digits = "".join(character for character in cleaned if character.isdigit())
        non_phone_characters = "".join(character for character in cleaned if not (character.isdigit() or character in " +-()"))
        if non_phone_characters or not digits:
            return AnswerValidation(valid=False, message="Please enter a phone number using digits only.")
        if validation_metadata.exact_length is not None and len(digits) != validation_metadata.exact_length:
            return AnswerValidation(
                valid=False,
                message=f"This form asks for exactly {validation_metadata.exact_length} digits; you entered {len(digits)}.",
            )

    if field.type == "email" or validation_metadata.value_format == "email":
        local, separator, domain = cleaned.partition("@")
        if (
            not separator
            or not local
            or not domain
            or "." not in domain
            or domain.startswith(".")
            or domain.endswith(".")
            or " " in cleaned
            or cleaned.count("@") != 1
        ):
            return AnswerValidation(valid=False, message="Please enter an email in the format name@example.com.")

    if field.type == "number" or validation_metadata.numeric_only or validation_metadata.value_format == "numeric":
        try:
            Decimal(cleaned)
        except InvalidOperation:
            return AnswerValidation(valid=False, message="Please enter a number.")

    if field.type == "date" or validation_metadata.value_format == "date":
        accepted_formats = _date_formats_for_field(field, validation_metadata)
        if not any(_is_date_in_format(cleaned, date_format) for date_format in accepted_formats):
            return AnswerValidation(valid=False, message="Please enter a complete valid date in the format requested by the form.")

    if field.options:
        selected_options = [item.strip() for item in cleaned.split(",") if item.strip()]
        if field.type != "checkbox" and len(selected_options) != 1:
            return AnswerValidation(valid=False, message="Please choose one visible option.")
        visible_options = {option.casefold() for option in field.options}
        if not selected_options or any(option.casefold() not in visible_options for option in selected_options):
            return AnswerValidation(
                valid=False,
                message="Please choose one of the visible options: " + ", ".join(field.options),
            )

    if validation_metadata.confidence == "high":
        length_error = _validate_length(cleaned, validation_metadata)
        if length_error:
            return AnswerValidation(valid=False, message=length_error)

    return AnswerValidation(valid=True)


def _is_date_in_format(value: str, date_format: str) -> bool:
    try:
        datetime.strptime(value, date_format)
        return True
    except ValueError:
        return False


def _date_formats_for_field(field: FormField, validation: ValidationMetadata) -> tuple[str, ...]:
    """Use an explicitly visible date format when present; otherwise standard parsing only."""

    visible_text = " ".join([*field.visible_instructions, *( [validation.date_format] if validation.date_format else [])]).upper().replace(" ", "")
    visible_formats = {
        "DD/MM/YYYY": "%d/%m/%Y",
        "DD-MM-YYYY": "%d-%m-%Y",
        "YYYY-MM-DD": "%Y-%m-%d",
    }
    detected = tuple(format_code for marker, format_code in visible_formats.items() if marker in visible_text)
    return detected or ("%Y-%m-%d", "%d/%m/%Y", "%d-%m-%Y")


def _effective_validation(field: FormField) -> ValidationMetadata:
    """Use model metadata, retaining legacy explicit extraction fields safely."""

    metadata = field.validation.model_copy(deep=True)
    if metadata.exact_length is None and field.expected_digits is not None:
        metadata.exact_length = field.expected_digits
    if metadata.value_format is None:
        if field.type == "email":
            metadata.value_format = "email"
        elif field.type == "date":
            metadata.value_format = "date"
        elif field.type == "number":
            metadata.value_format = "numeric"
    return metadata


def _length_instruction(validation: ValidationMetadata) -> str | None:
    if validation.min_length is not None and validation.max_length is not None:
        return f"The form specifies between {validation.min_length} and {validation.max_length} characters or digits."
    if validation.min_length is not None:
        return f"The form specifies at least {validation.min_length} characters or digits."
    if validation.max_length is not None:
        return f"The form specifies at most {validation.max_length} characters or digits."
    return None


def _validate_length(value: str, validation: ValidationMetadata) -> str | None:
    length = len(value)
    if validation.exact_length is not None and length != validation.exact_length:
        return f"This form asks for exactly {validation.exact_length} characters or digits; you entered {length}."
    if validation.min_length is not None and length < validation.min_length:
        return f"This form asks for at least {validation.min_length} characters or digits."
    if validation.max_length is not None and length > validation.max_length:
        return f"This form allows at most {validation.max_length} characters or digits."
    return None


def _is_user_question(value: str) -> bool:
    normalized = value.strip().casefold()
    question_starts = ("what", "why", "how", "where", "when", "which", "can you", "could you", "do i", "is this", "tell me", "explain", "help")
    return normalized.endswith("?") or normalized.startswith(question_starts)


YES_RESPONSES = {"yes", "y", "yeah", "yep", "correct", "right"}
NO_RESPONSES = {"no", "n", "nope", "incorrect", "wrong"}


def next_question(form: FormSchema, answered_field_ids: Collection[str] = ()) -> FormQuestion | None:
    """Return the first visible field not yet answered, or None when complete."""

    answered = set(answered_field_ids)
    for field in form.fields:
        if field.id not in answered:
            return question_for_field(field)
    return None


def collect_confirmed_answers(
    form: FormSchema,
    input_fn: Callable[[str], str] = input,
    output_fn: Callable[[str], None] = print,
) -> AnswerSession:
    """Ask extracted fields in order and retain only user-confirmed text.

    The AI never evaluates answers here. Only deterministic backend checks run,
    and only user-confirmed values are returned.
    """

    answers: list[ConfirmedAnswer] = []
    for field in form.fields:
        question = question_for_field(field)
        output_fn(f"\n{question.prompt}")
        if question.explanation:
            output_fn(question.explanation)
        output_fn(question.instruction)

        while True:
            value = input_fn("> ")
            if _is_user_question(value):
                output_fn(explain_field(field, value))
                continue
            validation = validate_answer(field, value)
            if not validation.valid:
                output_fn(validation.message or "That value cannot be accepted. Please try again.")
                continue
            while True:
                confirmation = input_fn(f"You entered: {value!r}. Is this correct? (yes/no): ").strip().lower()
                if _is_user_question(confirmation):
                    output_fn(explain_field(field, confirmation))
                    continue
                if confirmation in YES_RESPONSES:
                    answers.append(ConfirmedAnswer(field_id=field.id, value=value))
                    break
                if confirmation in NO_RESPONSES:
                    output_fn("Please enter the value again.")
                    break
                output_fn("Please answer yes or no.")
            if answers and answers[-1].field_id == field.id:
                break

    return AnswerSession(form_name=form.form_name, answers=answers)
